In [1]:
import pandas as pd
import numpy as np

# Load cleaned dataset

df = pd.read_csv(
    '../data/processed/churn_cleaned.csv'
)

df.head()

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,0.000131,4.100838e-05,9.084737e-04,2.086294,99.530517,44.235794,2.086425,9.953056e+01,4.423670e+01,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,0.000003,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,0.000004,9.450150e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450150e-08,0.000000e+00,0
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,...,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,...,0.000011,2.896760e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.896760e-06,4.860000e-10,0


In [2]:
# Dataset shape

print("Shape:", df.shape)

# Column names

print("\nColumns:\n")
print(df.columns)

# Datatypes

print("\nDatatypes:\n")
print(df.dtypes)

Shape: (14606, 44)

Columns:

Index(['id', 'channel_sales', 'cons_12m', 'cons_gas_12m', 'cons_last_month',
       'date_activ', 'date_end', 'date_modif_prod', 'date_renewal',
       'forecast_cons_12m', 'forecast_cons_year', 'forecast_discount_energy',
       'forecast_meter_rent_12m', 'forecast_price_energy_off_peak',
       'forecast_price_energy_peak', 'forecast_price_pow_off_peak', 'has_gas',
       'imp_cons', 'margin_gross_pow_ele', 'margin_net_pow_ele', 'nb_prod_act',
       'net_margin', 'num_years_antig', 'origin_up', 'pow_max',
       'var_year_price_off_peak_var', 'var_year_price_peak_var',
       'var_year_price_mid_peak_var', 'var_year_price_off_peak_fix',
       'var_year_price_peak_fix', 'var_year_price_mid_peak_fix',
       'var_year_price_off_peak', 'var_year_price_peak',
       'var_year_price_mid_peak', 'var_6m_price_off_peak_var',
       'var_6m_price_peak_var', 'var_6m_price_mid_peak_var',
       'var_6m_price_off_peak_fix', 'var_6m_price_peak_fix',
       'var_6m_

In [3]:
# Convert date columns to datetime

date_columns = [
    'date_activ',
    'date_end',
    'date_modif_prod',
    'date_renewal'
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col])

# Check datatypes again

df[date_columns].dtypes

date_activ         datetime64[us]
date_end           datetime64[us]
date_modif_prod    datetime64[us]
date_renewal       datetime64[us]
dtype: object

In [4]:
# Create tenure-related features

df['customer_tenure_days'] = (
    df['date_end'] - df['date_activ']
).dt.days

df['days_since_modification'] = (
    df['date_end'] - df['date_modif_prod']
).dt.days

df['days_since_renewal'] = (
    df['date_end'] - df['date_renewal']
).dt.days

# Preview new features

df[[
    'customer_tenure_days',
    'days_since_modification',
    'days_since_renewal'
]].head()

,customer_tenure_days,days_since_modification,days_since_renewal
0,1096,227,358
1,2566,2566,365
2,2192,2192,365
3,2192,2192,365
4,2245,2245,364


In [5]:
df.columns

Index(['id', 'channel_sales', 'cons_12m', 'cons_gas_12m', 'cons_last_month',
       'date_activ', 'date_end', 'date_modif_prod', 'date_renewal',
       'forecast_cons_12m', 'forecast_cons_year', 'forecast_discount_energy',
       'forecast_meter_rent_12m', 'forecast_price_energy_off_peak',
       'forecast_price_energy_peak', 'forecast_price_pow_off_peak', 'has_gas',
       'imp_cons', 'margin_gross_pow_ele', 'margin_net_pow_ele', 'nb_prod_act',
       'net_margin', 'num_years_antig', 'origin_up', 'pow_max',
       'var_year_price_off_peak_var', 'var_year_price_peak_var',
       'var_year_price_mid_peak_var', 'var_year_price_off_peak_fix',
       'var_year_price_peak_fix', 'var_year_price_mid_peak_fix',
       'var_year_price_off_peak', 'var_year_price_peak',
       'var_year_price_mid_peak', 'var_6m_price_off_peak_var',
       'var_6m_price_peak_var', 'var_6m_price_mid_peak_var',
       'var_6m_price_off_peak_fix', 'var_6m_price_peak_fix',
       'var_6m_price_mid_peak_fix', 'var_6m_p

In [6]:
# Check categorical columns  :  Encoding helps convert: customer categories , sales channels , service information into ML-understandable patterns.

categorical_columns = df.select_dtypes(include=['object']).columns

print(categorical_columns)

Index(['id', 'channel_sales', 'has_gas', 'origin_up'], dtype='str')


C:\Users\sneha\AppData\Local\Temp\ipykernel_6512\3545671886.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns


In [7]:
# One-hot encoding categorical variables

df_encoded = pd.get_dummies(
    df,
    columns=categorical_columns,
    drop_first=True
)

# Check new shape

print("Encoded Shape:", df_encoded.shape)

# Preview dataset

df_encoded.head()

Encoded Shape: (14606, 14661)


,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,...,channel_sales_foosdfpfkusacimwkcsosbicdxkicaua,channel_sales_lmkebamcaaclubfxadlmueccxoimlema,channel_sales_sddiedcslfslkckwlfkdpoeeailfpeds,channel_sales_usilxuppasemubllopkaafesmlibmsdf,has_gas_t,origin_up_ewxeelcelemmiwuafmddpobolfuxioce,origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws,origin_up_ldkssxwpmemidmecebumciepifcamkci,origin_up_lxidpiddsbxsbosboudacockeimpuepw,origin_up_usapbepcfoloekilkwsdiboslwaxobdp
0,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,0,0,...,True,False,False,False,True,False,False,False,True,False
1,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,0,0,...,False,False,False,False,False,False,True,False,False,False
2,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,0,0,...,True,False,False,False,False,False,True,False,False,False
3,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,0,0,...,False,True,False,False,False,False,True,False,False,False
4,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,526,0,...,False,False,False,False,False,False,True,False,False,False


## Categorical Encoding

Machine Learning models cannot directly understand text-based categorical values such as:

* `channel_sales`
* `has_gas`
* `origin_up`

ML algorithms work with numerical data, so categorical variables must be converted into numeric format before model training.

For this project, One-Hot Encoding is used using `pd.get_dummies()`.

### Why One-Hot Encoding?

One-Hot Encoding creates separate binary columns for each category.

Example:

| has_gas | has_gas_t |
| ------- | --------- |
| t       | 1         |
| f       | 0         |

This helps the model understand category-based patterns without assigning incorrect numerical order to categories.

### Why `drop_first=True`?

`drop_first=True` removes one category from each encoded feature to avoid redundant information.

This is a professional Machine Learning practice used to reduce:

* multicollinearity
* duplicate feature information
* unnecessary complexity in the dataset

For example, if a variable has:

* Yes
* No

then keeping both columns is unnecessary because one column can already explain the other.

### Business Value

Encoding helps transform customer-related categorical information into ML-readable patterns, allowing the churn prediction model to learn relationships between:

* customer acquisition channels
* gas subscription status
* customer origin categories
* and churn behavior.


In [8]:
# Separate features and target

X = df_encoded.drop('churn', axis=1)

y = df_encoded['churn']

# Check shapes

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (14606, 14660)
y shape: (14606,)


## Separating Features and Target Variable

The dataset is divided into:

* `X` → input features
* `y` → target variable (`churn`)

`X` contains customer-related information such as consumption, pricing, tenure, and other engineered features.
`y` contains the churn column that the model will predict.

This step is important because Machine Learning models learn patterns from the input features (`X`) to predict the target variable (`y`).


In [9]:
from sklearn.model_selection import train_test_split

# Split dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Check shapes

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (11684, 14660)
X_test shape: (2922, 14660)
y_train shape: (11684,)
y_test shape: (2922,)


## Train-Test Split

The dataset is divided into training and testing sets using `train_test_split()`.

* Training data is used to train the Machine Learning model.
* Testing data is used to evaluate model performance on unseen data.

Here:

* `80%` data is used for training
* `20%` data is used for testing


In [10]:
X_train.select_dtypes(include=['datetime']).columns

Index(['date_activ', 'date_end', 'date_modif_prod', 'date_renewal'], dtype='str')

In [11]:
print(df.columns)


Index(['id', 'channel_sales', 'cons_12m', 'cons_gas_12m', 'cons_last_month',
       'date_activ', 'date_end', 'date_modif_prod', 'date_renewal',
       'forecast_cons_12m', 'forecast_cons_year', 'forecast_discount_energy',
       'forecast_meter_rent_12m', 'forecast_price_energy_off_peak',
       'forecast_price_energy_peak', 'forecast_price_pow_off_peak', 'has_gas',
       'imp_cons', 'margin_gross_pow_ele', 'margin_net_pow_ele', 'nb_prod_act',
       'net_margin', 'num_years_antig', 'origin_up', 'pow_max',
       'var_year_price_off_peak_var', 'var_year_price_peak_var',
       'var_year_price_mid_peak_var', 'var_year_price_off_peak_fix',
       'var_year_price_peak_fix', 'var_year_price_mid_peak_fix',
       'var_year_price_off_peak', 'var_year_price_peak',
       'var_year_price_mid_peak', 'var_6m_price_off_peak_var',
       'var_6m_price_peak_var', 'var_6m_price_mid_peak_var',
       'var_6m_price_off_peak_fix', 'var_6m_price_peak_fix',
       'var_6m_price_mid_peak_fix', 'var_6m_p

In [12]:
df.drop(
    columns=[
        'id',
        'date_activ',
        'date_end',
        'date_modif_prod',
        'date_renewal'
    ],
    inplace=True
)

print(df.shape)

(14606, 42)


In [13]:
df.columns

Index(['channel_sales', 'cons_12m', 'cons_gas_12m', 'cons_last_month',
       'forecast_cons_12m', 'forecast_cons_year', 'forecast_discount_energy',
       'forecast_meter_rent_12m', 'forecast_price_energy_off_peak',
       'forecast_price_energy_peak', 'forecast_price_pow_off_peak', 'has_gas',
       'imp_cons', 'margin_gross_pow_ele', 'margin_net_pow_ele', 'nb_prod_act',
       'net_margin', 'num_years_antig', 'origin_up', 'pow_max',
       'var_year_price_off_peak_var', 'var_year_price_peak_var',
       'var_year_price_mid_peak_var', 'var_year_price_off_peak_fix',
       'var_year_price_peak_fix', 'var_year_price_mid_peak_fix',
       'var_year_price_off_peak', 'var_year_price_peak',
       'var_year_price_mid_peak', 'var_6m_price_off_peak_var',
       'var_6m_price_peak_var', 'var_6m_price_mid_peak_var',
       'var_6m_price_off_peak_fix', 'var_6m_price_peak_fix',
       'var_6m_price_mid_peak_fix', 'var_6m_price_off_peak',
       'var_6m_price_peak', 'var_6m_price_mid_peak', 'chur

In [14]:
X.select_dtypes(include=['object', 'string']).columns

Index([], dtype='str')

In [15]:
print(X.select_dtypes(include=['datetime']).columns)

Index(['date_activ', 'date_end', 'date_modif_prod', 'date_renewal'], dtype='str')


In [16]:
print(df.select_dtypes(include=['datetime']).columns)

Index([], dtype='str')


In [17]:
X = df.drop('churn', axis=1)
y = df['churn']

In [18]:
X.select_dtypes(include=['datetime']).columns

Index([], dtype='str')

In [19]:
print(X.select_dtypes(include=['object', 'string']).columns)


Index(['channel_sales', 'has_gas', 'origin_up'], dtype='str')


In [20]:
# Convert categorical variables into numerical variables

df = pd.get_dummies(
    df,
    columns=['channel_sales', 'has_gas', 'origin_up'],
    drop_first=True
)

# Verify that no categorical columns remain

print(df.select_dtypes(include=['object', 'string']).columns)

Index([], dtype='str')


In [21]:
# Features and target

X = df.drop('churn', axis=1)
y = df['churn']

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
# training model
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train_scaled, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [25]:
# Predict churn for test data

y_pred = log_model.predict(X_test_scaled)

# View first 10 predictions

print(y_pred[:10])

[0 0 0 0 0 0 0 0 0 0]


In [26]:
# Count predicted classes

import pandas as pd

pd.Series(y_pred).value_counts()

0    2915
1       7
Name: count, dtype: int64

### Model Prediction Summary

The Logistic Regression model predicted that **2,915 customers will stay** and only **7 customers will churn** out of 2,922 customers in the test dataset. However, during EDA we found that approximately **9.7% of customers are churners**, which suggests that the test data should contain a much higher number of churn cases.

This indicates that the model is predicting the majority class (non-churn) for almost all customers and is struggling to identify churners correctly. This is a common issue in **imbalanced datasets**, where one class significantly outnumbers the other. Therefore, accuracy alone may not be sufficient to evaluate model performance, and additional metrics such as Precision, Recall, F1-Score, and Confusion Matrix should be analyzed.


In [27]:
# accuracy testing
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8959616700889802


Accuracy Evaluation

The performance of the Logistic Regression model was initially evaluated using Accuracy Score. Accuracy measures the proportion of correctly classified observations out of the total observations in the test dataset. 

The model achieved an accuracy of 89.6%, but this does not necessarily indicate strong churn prediction performance because the model predicted very few customers as churners. Since the dataset is imbalanced, additional evaluation metrics are required to assess how effectively the model identifies churned customers.

In [28]:
# confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[2614    3]
 [ 301    4]]


## Confusion Matrix Analysis

The Confusion Matrix revealed that the Logistic Regression model correctly classified 2,614 non-churn customers and incorrectly classified only 3 non-churn customers as churners.

However, the model struggled to identify churned customers. Out of 305 actual churn customers, only 4 were correctly identified, while 301 churn customers were incorrectly classified as non-churners.

Although the model achieved a high accuracy score, the confusion matrix indicates that it is heavily biased toward predicting the majority class (non-churn). As a result, the model is not effective at detecting customers who are likely to churn, which is the primary business objective of this project.


In [29]:
# classificaion_report
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95      2617
           1       0.57      0.01      0.03       305

    accuracy                           0.90      2922
   macro avg       0.73      0.51      0.49      2922
weighted avg       0.86      0.90      0.85      2922



## Classification Report Analysis

The Classification Report shows that the Logistic Regression model performs very well in identifying non-churn customers, achieving a Recall of 1.00 and an F1-Score of 0.95 for Class 0.

However, the model performs poorly for churn customers (Class 1). The Recall score is only 0.01, indicating that the model identifies only a very small fraction of actual churners. The F1-Score of 0.03 further confirms weak performance for the churn class.

These results suggest that the model is heavily biased toward the majority class (non-churn customers) and struggles to detect customers who are likely to leave. 

In [30]:
from sklearn.linear_model import LogisticRegression

# Logistic Regression with class balancing

balanced_model = LogisticRegression(
    class_weight='balanced',
    max_iter=1000
)

# Train model

balanced_model.fit(X_train_scaled, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",'balanced'
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :ter

## Handling Class Imbalance

The customer churn dataset is highly imbalanced, with significantly fewer churn customers compared to non-churn customers.

To address this issue, Logistic Regression was trained using the `class_weight='balanced'` parameter. This technique automatically assigns higher importance to the minority class (churn customers) during training, helping the model learn churn patterns more effectively.

The objective is to improve the model's ability to identify churn customers while maintaining reasonable overall performance.

In [31]:
# Make predictions using balanced model

y_pred_balanced = balanced_model.predict(X_test_scaled)

# Count predictions

import pandas as pd

print(pd.Series(y_pred_balanced).value_counts())

0    1687
1    1235
Name: count, dtype: int64


In [ ]:
# accuracy of balanced model
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred_balanced)

print("Accuracy:", accuracy)


Accuracy: 0.5879534565366188


In [33]:
# confusion matrix for balanced model 
from sklearn.metrics import confusion_matrix

cm_balanced = confusion_matrix(y_test, y_pred_balanced)

print(cm_balanced)

[[1550 1067]
 [ 137  168]]


## Confusion Matrix Analysis (Balanced Model)

The balanced Logistic Regression model significantly improved churn detection performance.

The model correctly identified 168 churn customers, compared to only 4 churn customers detected by the original Logistic Regression model. However, this improvement came at the cost of a higher number of false positives, where 1,067 non-churn customers were incorrectly classified as churners.

From a business perspective, the balanced model provides better support for customer retention strategies because it identifies a much larger proportion of customers at risk of leaving. Although some loyal customers may be incorrectly flagged, the cost of missing actual churn customers is often higher than the cost of unnecessary retention efforts.

In [34]:
# Classification Report for Balanced Model
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_balanced))

              precision    recall  f1-score   support

           0       0.92      0.59      0.72      2617
           1       0.14      0.55      0.22       305

    accuracy                           0.59      2922
   macro avg       0.53      0.57      0.47      2922
weighted avg       0.84      0.59      0.67      2922



In [35]:
# Get feature importance from Logistic Regression

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': balanced_model.coef_[0]
})

# Sort by importance

feature_importance = feature_importance.sort_values(
    by='Coefficient',
    ascending=False
)

# Top 15 features

feature_importance.head(15)

,Feature,Coefficient
49,origin_up_lxidpiddsbxsbosboudacockeimpuepw,0.622182
48,origin_up_ldkssxwpmemidmecebumciepifcamkci,0.398368
9,forecast_price_pow_off_peak,0.316458
28,var_6m_price_mid_peak_var,0.294097
47,origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws,0.286292
14,net_margin,0.223471
12,margin_net_pow_ele,0.220992
22,var_year_price_mid_peak_fix,0.209120
25,var_year_price_mid_peak,0.209104
11,margin_gross_pow_ele,0.176056


## Key Churn Drivers Identified

Feature importance analysis revealed that pricing-related variables were among the strongest predictors of customer churn. Several features related to forecasted energy prices and price variations over time showed a strong positive association with churn probability.

Consumption-related features also contributed to churn prediction, indicating that customer usage patterns influence retention behavior.

Additionally, margin-related variables appeared among the top predictors, suggesting that customer profitability and churn may be related. These findings support the hypothesis that pricing strategy and customer value management are important factors in reducing customer churn.